import * as THREE from 'three';
import {Sequencer,clipNames} from './sequencer.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {TransformControls} from './vendor/TransformControls.js';

const $=id=>document.getElementById(id), clone=v=>structuredClone(v);
let scene=null,map=null,catalog=[],looks={},selected=null,eventId=null,tab='actor',dirty=false,routeMode=false,manual=false;
let live={state:'idle',actors:{},events:[]},lastRun=null,history=[],redo=[],sceneOptions=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const actionNames={speed:'目标速度',brake:'制动',lane_change:'变道',offset:'横向偏移',follow:'跟随车辆',route:'沿绘制路线行驶',lights:'车辆灯光',weather:'切换光影',destroy:'移除参与者',spawn:'生成参与者',marker:'事件标记',finish:'结束场景'};
const triggerNames={time:'仿真时间',position:'通过坐标',distance:'参与者间距离',point:'接近地点',speed:'参与者速度',after_event:'另一事件之后'};
function toast(text,error=false){$('toast').textContent=text;$('toast').className=error?'error':'';$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',6000)}
async function api(path,data){const r=await fetch('/api/'+path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error||r.statusText);return v}
function guarded(fn){return async(...args)=>{try{return await fn(...args)}catch(e){toast(e.message,true);console.error(e)}}}
function checkpoint(){if(!scene)return;history.push(JSON.stringify(scene));history=history.slice(-50);redo=[]}
function changed(){dirty=true;$('dirty').textContent='● 未保存';requestRender=true;schedulePlan();updateMode()}
function actor(){return scene?.actors.find(a=>a.id===selected)}
function event(){return scene?.events.find(e=>e.id===eventId)}
function confirmChange(text){return new Promise(resolve=>{const d=$('confirm');$('confirm-text').textContent=text;d.showModal();$('confirm-ok').onclick=()=>{d.close();resolve(true)};$('confirm-cancel').onclick=()=>{d.close();resolve(false)}})}
function options(values,current){return Object.entries(values).map(([v,n])=>`<option value="${esc(v)}" ${v==current?'selected':''}>${esc(n)}</option>`).join('')}
function field(name,label,value,type='number',extra=''){return `<label class="field"><span>${label}</span><input data-key="${name}" aria-label="${label}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function select(name,label,values,current){return `<label class="field"><span>${label}</span><select data-key="${name}" aria-label="${label}">${options(values,current)}</select></label>`}
const actorOptions=()=>Object.fromEntries(scene.actors.map(a=>[a.id,a.name]));

// All geometry here is an authoring proxy. CARLA RGB is shown separately.
const viewport=$('viewport'),world=new THREE.Scene();world.background=new THREE.Color('#142230');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));viewport.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(48,1,.1,10000);camera.position.set(65,110,105);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.dampingFactor=.12;orbit.maxPolarAngle=Math.PI*.49;
const gizmo=new TransformControls(camera,renderer.domElement);world.add(gizmo.getHelper());
gizmo.showY=false;gizmo.addEventListener('dragging-changed',e=>orbit.enabled=!e.value);
world.add(new THREE.HemisphereLight(0xcdeeff,0x425246,2.4));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(50,100,80);world.add(sun);
let origin={x:693,y:-537,z:8.5},roadGroup=new THREE.Group(),actorGroup=new THREE.Group(),routeGroup=new THREE.Group(),actorMeshes=new Map(),requestRender=true;
world.add(roadGroup,actorGroup,routeGroup);
const grid=new THREE.GridHelper(5000,500,0x385260,0x203440);grid.position.y=-.12;world.add(grid);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(7000,7000),new THREE.MeshLambertMaterial({color:0x192c31}));ground.rotation.x=-Math.PI/2;ground.position.y=-.15;world.add(ground);
function to3(p){return new THREE.Vector3(p.x-origin.x,(p.z??origin.z)-origin.z,-(p.y-origin.y))}
function from3(p){return {x:p.x+origin.x,y:origin.y-p.z,z:p.y+origin.z}}
const resize=new ResizeObserver(()=>{const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();requestRender=true});resize.observe(viewport);
function draw(){requestAnimationFrame(draw);if(orbit.update())requestRender=true;if(requestRender){renderer.render(world,camera);requestRender=false}}draw();
function disposeGroup(group){while(group.children.length){const o=group.children[0];group.remove(o);o.traverse(n=>{n.geometry?.dispose();if(n.material&&!Array.isArray(n.material)){n.material.map?.dispose();n.material.dispose()}})}}
function drawMap(){disposeGroup(roadGroup);const positions=[],linePoints=[];
 for(const lane of map.lanes){for(let i=0;i<lane.length-1;i++){const a=lane[i],b=lane[i+1];if(Math.hypot(b[1]-a[1],b[2]-a[2])>15)continue;
 const corners=[];for(const p of [a,b]){const yaw=p[4]*Math.PI/180,w=p[5]/2;for(const side of [-1,1])corners.push(to3({x:p[1]-Math.sin(yaw)*w*side,y:p[2]+Math.cos(yaw)*w*side,z:p[3]+.015}))}
 for(const index of [0,1,2,2,1,3])positions.push(...corners[index]);
 if(i%3===0){linePoints.push(...to3({x:a[1],y:a[2],z:a[3]+.055}),...to3({x:b[1],y:b[2],z:b[3]+.055}))}}
 }
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.computeVertexNormals();roadGroup.add(new THREE.Mesh(g,new THREE.MeshLambertMaterial({color:0x405363,side:THREE.DoubleSide})));
 const l=new THREE.BufferGeometry();l.setAttribute('position',new THREE.Float32BufferAttribute(linePoints,3));roadGroup.add(new THREE.LineSegments(l,new THREE.LineBasicMaterial({color:0x8cabb4,transparent:true,opacity:.5})));
 const boxes=map.buildings.filter(b=>b.ex>0&&b.ey>0&&b.ez>0&&b.ex<150&&b.ey<150);
 if(boxes.length){const inst=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshLambertMaterial({color:0x33454f,transparent:true,opacity:.48}),boxes.length),m=new THREE.Object3D();boxes.forEach((b,i)=>{m.position.copy(to3(b));m.scale.set(b.ex*2,b.ez*2,b.ey*2);m.rotation.y=(b.yaw||0)*Math.PI/180;m.updateMatrix();inst.setMatrixAt(i,m.matrix)});roadGroup.add(inst)}
 $('map-loading').style.display='none';requestRender=true;
}
function labelSprite(text){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle='#142230dd';ctx.fillRect(0,0,512,96);ctx.fillStyle='#e0f3ff';ctx.font='32px "Microsoft YaHei",sans-serif';ctx.textAlign='center';ctx.fillText(text,256,62);const t=new THREE.CanvasTexture(c),sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:t,depthTest:false}));sprite.scale.set(12,2.25,1);sprite.position.y=5;return sprite}
function model(a){const group=new THREE.Group(),ped=a.model.startsWith('walker'),prop=a.model.startsWith('static'),truck=a.model.includes('firetruck'),bike=a.model.includes('ninja');
 const color=new THREE.Color(a.color||'#d5dce1'),material=new THREE.MeshLambertMaterial({color});
 const body=new THREE.Mesh(ped?new THREE.CapsuleGeometry(.27,1.1,4,8):new THREE.BoxGeometry(truck?9:bike?2.2:prop?1.2:4.4,ped?1.6:truck?2.4:bike?.8:prop?1.2:1,truck?2.7:bike?.7:prop?1.2:1.85),material);body.position.y=ped?.9:truck?1.4:.65;group.add(body);
 if(!ped&&!prop){const cabin=new THREE.Mesh(new THREE.BoxGeometry(truck?2.3:2.1,.65,truck?2.5:1.65),new THREE.MeshLambertMaterial({color:0x224c62}));cabin.position.set(truck?2.8:-.25,truck?2.5:1.4,0);group.add(cabin);
 const wheelmat=new THREE.MeshLambertMaterial({color:0x0d1720});for(const x of [-1.4,1.4])for(const z of [-.95,.95]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.22,10),wheelmat);wheel.rotation.x=Math.PI/2;wheel.position.set(x,.4,z);group.add(wheel)}}
 const arrow=new THREE.ArrowHelper(new THREE.Vector3(1,0,0),new THREE.Vector3(0,.2,0),truck?7:4,a.id===scene.ego?0x68e3c0:0xedc77d,1,.7);group.add(arrow);group.add(labelSprite((a.id===scene.ego?'● ':'')+a.name));group.userData.actorId=a.id;return group;
}
function rebuildActors(){gizmo.detach();disposeGroup(actorGroup);actorMeshes.clear();for(const a of scene.actors){const group=model(a);group.position.copy(to3(a));group.rotation.y=a.yaw*Math.PI/180;actorGroup.add(group);actorMeshes.set(a.id,group)}attach();drawRoutes();requestRender=true}
function attach(){const obj=actorMeshes.get(selected);if(obj&&!motionLocked()&&!routeMode)gizmo.attach(obj);else gizmo.detach()}
function drawRoutes(){disposeGroup(routeGroup);for(const a of scene.actors){if(!a.route?.length)continue;const points=[to3(a),...a.route.map(p=>to3({...p,z:(p.z||a.z)+.2}))];const g=new THREE.BufferGeometry().setFromPoints(points);routeGroup.add(new THREE.Line(g,new THREE.LineBasicMaterial({color:a.id===selected?0x75ecd0:0x647e8d})));for(let i=1;i<points.length;i++){const dot=new THREE.Mesh(new THREE.SphereGeometry(.7,8,6),new THREE.MeshBasicMaterial({color:0x75ecd0}));dot.position.copy(points[i]);routeGroup.add(dot)}}requestRender=true}
gizmo.addEventListener('mouseDown',()=>checkpoint());
gizmo.addEventListener('objectChange',()=>{if(!gizmo.object||!actor()||motionLocked())return;Object.assign(actor(),from3(gizmo.object.position),{yaw:gizmo.object.rotation.y*180/Math.PI});changed();drawRoutes()});
gizmo.addEventListener('mouseUp',guarded(async()=>{const a=actor();if(!a||motionLocked())return;if(gizmo.mode==='translate')a.snap=$('snap').checked&&!a.model.startsWith('walker');if(gizmo.mode==='translate'&&$('snap').checked&&!a.model.startsWith('walker')){const snapped=await api('snap',a);Object.assign(a,snapped)}if(live.state==='preview')await api('command',{type:'transform',actor:a.id,pose:a});rebuildActors();renderProperties()}));
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null;
renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});
renderer.domElement.addEventListener('pointerup',guarded(async e=>{if(e.button!==0||gizmo.dragging||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>4)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);
 if(routeMode&&actor()&&!motionLocked()){const p=new THREE.Vector3();if(ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),p)){checkpoint();let point=from3(p);if(!actor().model.startsWith('walker'))point=await api('snap',point);actor().route.push({x:point.x,y:point.y,z:point.z});changed();drawRoutes();renderProperties()}return}
 const hits=ray.intersectObjects(actorGroup.children,true);if(hits.length){let o=hits[0].object;while(o&&!o.userData.actorId)o=o.parent;if(o)selectActor(o.userData.actorId)}}));
function focus(){camera.up.set(0,1,0);const a=actor()||scene.actors[0];if(!a)return;const p=to3(a);orbit.target.copy(p);camera.position.copy(p).add(new THREE.Vector3(28,42,45));orbit.update();requestRender=true}

function selectActor(id){selected=id;$('snap').checked=actor()?.snap!==false;tab='actor';render();attach()}
function renderList(){$('actor-list').innerHTML=scene.actors.map(a=>`<div class="actor-item ${a.id===selected?'selected':''}" data-actor="${esc(a.id)}"><b><span class="dot" style="background:${/^#[0-9a-f]{6}$/i.test(a.color)?a.color:'#69cdb7'}"></span>${esc(a.name)} ${a.id===scene.ego?'· 主视角':''}</b><small>${esc(a.model.split('.').slice(1).join(' '))} · ${a.speed} km/h</small></div>`).join('');document.querySelectorAll('[data-actor]').forEach(el=>el.onclick=()=>selectActor(el.dataset.actor))}
function triggerText(t){if(t.type==='time')return `${t.value} s`;if(t.type==='after_event')return `${t.event} + ${t.value}s`;if(t.type==='point')return `距 (${t.x?.toFixed?.(1)}, ${t.y?.toFixed?.(1)}) ≤ ${t.value}m`;return `${t.actor} ${t.type==='position'?t.axis:t.type==='distance'?'距 '+t.target:'速度'} ${t.op||'>='} ${t.value}`}
function renderEvents(){$('event-list').innerHTML=scene.events.map((e,i)=>`<div class="event-item ${e.id===eventId?'selected':''} ${e.id in (live.fired||{})?'fired':''}" data-event="${esc(e.id)}"><span>${String(i+1).padStart(2,'0')}</span><div>${esc(e.name||actionNames[e.action.type])}<div class="trigger">${esc(triggerText(e.trigger))} → ${esc(e.action.actor||'场景')} ${esc(actionNames[e.action.type])} ${esc(e.action.value??'')}</div></div><span>${e.enabled===false?'停用':e.id in (live.fired||{})?'✓ 已触发':''}</span></div>`).join('');document.querySelectorAll('[data-event]').forEach(el=>el.onclick=()=>{eventId=el.dataset.event;tab='event';render()})}
function render(){if(!scene)return;$('scene-name').value=scene.name;$('duration').value=scene.duration;renderList();renderEvents();document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===tab));renderProperties();sequencer.render();updateMode();schedulePlan()}
function renderLegacyProperties(){const box=$('properties');if(!scene)return;
 if(tab==='actor'){const a=actor();if(!a){box.innerHTML='<p class="hint">选择一个参与者</p>';return}
 const models=Object.fromEntries(catalog.map(b=>[b.id,b.id]));models[a.model]=a.model;
 box.innerHTML=`<h3 class="prop-title">${esc(a.name)}</h3>${field('name','名称',a.name,'text')}${select('model','模型',models,a.model)}<div class="triple">${['x','y','z'].map(k=>`<label>${k.toUpperCase()} / m<input data-key="${k}" aria-label="${k.toUpperCase()} 坐标" type="number" step=".1" value="${a[k].toFixed(2)}"></label>`).join('')}</div>${field('yaw','朝向 / °',a.yaw.toFixed(1),'number','step="1"')}${field('color','颜色',a.color||'#d5dce1','color')}${select('behavior','基础行为',{scripted:'实验车辆 · 按事件运动',traffic:'普通交通 · 自适应跟车',parked:'静止障碍物',walker:'行人运动'},a.behavior)}${field('speed','速度 km/h',a.speed,'number','min="0" max="180" step=".5"')}${field('acceleration','加速度 m/s²',a.acceleration??2.5,'number','min=".1" max="12" step=".1"')}${field('deceleration','减速度 m/s²',a.deceleration??6,'number','min=".1" max="15" step=".1"')}${field('offset','左偏移 / m',a.offset??0,'number','step=".1"')}<label class="field"><span>行驶初态</span><input data-key="start_in_motion" type="checkbox" ${a.start_in_motion?'checked':''}>启动即具有目标速度</label><label class="field"><span>初始生成</span><input data-key="spawn_at_start" type="checkbox" ${a.spawn_at_start!==false?'checked':''}>否则由生成事件触发</label><div class="actions"><button id="set-ego">设为主视角</button><button id="snap-actor">吸附车道</button><button id="clone-actor">复制</button><button id="delete-actor" class="danger">移除</button></div><div class="subheading">路线 <small>点选地图添加路线点</small></div><div class="actions"><button id="edit-route">${routeMode?'完成绘制':'绘制路线'}</button><button id="clear-route">清空路线</button></div>${(a.route||[]).map((p,i)=>`<div class="route-point">${i+1}. ${p.x.toFixed(1)}, ${p.y.toFixed(1)}<button data-route-delete="${i}">×</button></div>`).join('')}<p class="hint">车辆路线沿道路网络规划；行人沿指定点移动。运行前编辑路线与速度，停止后可继续修改；运行中可随时手动接管。</p>`;
 box.querySelectorAll('[data-key]').forEach(el=>el.onchange=guarded(async()=>{checkpoint();a[el.dataset.key]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(['x','y','z'].includes(el.dataset.key))a.snap=false;if(el.dataset.key==='model')a.behavior=a.model.startsWith('walker.')?'walker':a.model.startsWith('static.')?'parked':'scripted';changed();rebuildActors();renderList();if(el.dataset.key==='model')renderProperties();if(live.state==='preview'&&['x','y','z','yaw'].includes(el.dataset.key))await api('command',{type:'transform',actor:a.id,pose:a})}));
 $('set-ego').onclick=guarded(async()=>{checkpoint();scene.ego=a.id;changed();rebuildActors();renderList();if(['preview','running','paused'].includes(live.state))await api('command',{type:'camera',actor:a.id,view:$('camera-view').value})});
 $('snap-actor').onclick=guarded(async()=>{checkpoint();Object.assign(a,await api('snap',a));a.snap=true;changed();rebuildActors();renderProperties();if(live.state==='preview')await api('command',{type:'transform',actor:a.id,pose:a})});
 $('clone-actor').onclick=()=>{checkpoint();const b=clone(a);b.id='actor_'+crypto.randomUUID().slice(0,8);b.name+=' 副本';b.clips=(b.clips||[]).map(c=>({...c,id:'clip_'+crypto.randomUUID().slice(0,8)}));b.y-=12;scene.actors.push(b);selected=b.id;changed();rebuildActors();render()};
 $('delete-actor').onclick=guarded(async()=>{if(scene.actors.length===1)throw Error('场景至少保留一个参与者');if(!(await confirmChange('移除此参与者以及引用它的事件？')))return;checkpoint();scene.actors=scene.actors.filter(b=>b.id!==a.id);for(const b of scene.actors)b.clips=(b.clips||[]).filter(c=>c.target!==a.id);scene.events=scene.events.filter(e=>![e.trigger.actor,e.trigger.target,e.action.actor,e.action.target].includes(a.id));let count;do{count=scene.events.length;const ids=new Set(scene.events.map(e=>e.id));scene.events=scene.events.filter(e=>e.trigger.type!=='after_event'||ids.has(e.trigger.event))}while(scene.events.length!==count);if(scene.ego===a.id)scene.ego=scene.actors[0].id;selected=scene.ego;changed();rebuildActors();render()});
 $('edit-route').onclick=toggleRoute;$('clear-route').onclick=()=>{checkpoint();a.route=[];changed();drawRoutes();renderProperties()};box.querySelectorAll('[data-route-delete]').forEach(el=>el.onclick=()=>{checkpoint();a.route.splice(+el.dataset.routeDelete,1);changed();drawRoutes();renderProperties()});
 }else if(tab==='event'){const e=event();if(!e){box.innerHTML='<p class="hint">选择或新建事件</p>';return}const t=e.trigger,a=e.action;
 let html=`<h3 class="prop-title">事件条件与动作</h3>${field('name','事件名称',e.name||'事件','text')}<label class="field"><span>启用</span><input data-key="enabled" type="checkbox" ${e.enabled!==false?'checked':''}></label><div class="subheading">当条件满足时（只触发一次）</div>${select('trigger.type','触发方式',triggerNames,t.type)}`;
 if(!['time','after_event'].includes(t.type))html+=select('trigger.actor','参与者',actorOptions(),t.actor);
 if(t.type==='distance')html+=select('trigger.target','距离目标',actorOptions(),t.target);
 if(t.type==='after_event')html+=select('trigger.event','前置事件',Object.fromEntries(scene.events.filter(x=>x.id!==e.id).map(x=>[x.id,x.name||x.id])),t.event);
 if(t.type==='position')html+=select('trigger.axis','坐标轴',{x:'X',y:'Y'},t.axis||'y');
 if(t.type==='point')html+=field('trigger.x','地点 X',t.x??693)+field('trigger.y','地点 Y',t.y??-537);
 if(!['time','after_event','point'].includes(t.type))html+=select('trigger.op','比较',{'>=':'大于或等于','<=':'小于或等于'},t.op||'>=');
 html+=field('trigger.value',['time','after_event'].includes(t.type)?'时间 / 秒':t.type==='speed'?'速度 km/h':'数值 / 米',t.value??0,'number','step=".1"');
 html+=`<div class="subheading">执行动作</div>${select('action.type','动作类型',actionNames,a.type)}`;
 if(!['weather','marker','finish'].includes(a.type))html+=select('action.actor','作用对象',actorOptions(),a.actor);
 if(['speed','brake','offset'].includes(a.type))html+=field('action.value',a.type==='speed'?'速度 km/h':a.type==='brake'?'制动 0–1':'左偏移 / m',a.value??0,'number','step=".1"');
 if(a.type==='lane_change')html+=select('action.direction','方向',{left:'左',right:'右'},a.direction||'left')+field('action.lanes','跨越车道数',a.lanes||1,'number','min="1" max="3"')+field('action.distance','变道距离 / m',a.distance||20,'number','min="5"');
 if(a.type==='follow')html+=select('action.target','跟随目标',actorOptions(),a.target)+field('action.reaction','反应延迟 / s',a.reaction??.8,'number','min="0" step=".1"')+field('action.gap','最小车距 / m',a.gap??3,'number','min="0" step=".1"');
 if(a.type==='weather')html+=select('action.preset','画面预设',Object.fromEntries(Object.entries(looks).map(([k,v])=>[k,v.name])),a.preset||'daylight');
 if(a.type==='lights')html+=select('action.value','灯光',{0:'关闭',3:'示宽灯 + 近光灯',17:'示宽灯 + 右转向灯',33:'示宽灯 + 左转向灯',49:'双闪'},a.value??3);
 if(a.type==='marker')html+=field('action.label','标记内容',a.label||'事件','text');
 html+='<div class="actions"><button id="execute-event">立即执行动作</button><button id="clone-event">复制事件</button><button id="delete-event" class="danger">删除事件</button></div><p class="hint">仿真时间不含暂停；位置和距离条件由真实车辆状态判断。事件标记不会自动播放接管提示音。</p>';box.innerHTML=html;
 box.querySelectorAll('[data-key]').forEach(el=>el.onchange=()=>{checkpoint();const [group,key]=el.dataset.key.split('.');let val=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(group==='action'&&key==='value'&&a.type==='lights')val=Number(val);if(key)e[group][key]=val;else e[group]=val;
 if(el.dataset.key==='trigger.type'){Object.assign(t,{actor:scene.ego,value:0,op:val==='distance'||val==='point'?'<=':'>=',axis:'y'});if(val==='distance')t.target=scene.actors.find(x=>x.id!==scene.ego)?.id||scene.ego;if(val==='after_event')t.event=scene.events.find(x=>x.id!==e.id)?.id;if(val==='point')Object.assign(t,{x:actor()?.x||693,y:actor()?.y||-537,value:5})}
 if(el.dataset.key==='action.type'){Object.assign(a,{actor:selected||scene.ego,value:val==='speed'?50:val==='brake'?1:0});if(val==='follow')a.target=scene.ego;if(val==='weather')a.preset='daylight'}changed();renderEvents();renderProperties()});
 $('execute-event').onclick=guarded(async()=>{await api('command',{type:'action',action:a});toast('动作已发送')});$('clone-event').onclick=()=>{checkpoint();const b=clone(e);b.id='event_'+crypto.randomUUID().slice(0,8);b.name+=' 副本';scene.events.push(b);eventId=b.id;changed();render()};$('delete-event').onclick=guarded(async()=>{if(scene.events.some(x=>x.trigger.event===e.id))throw Error('其他事件依赖此事件，请先修改依赖');checkpoint();scene.events=scene.events.filter(x=>x.id!==e.id);eventId=scene.events[0]?.id;changed();render()});
 }else{const look=scene.look,defaults=looks[look.preset]||{weather:{},camera:{}};const weather={...defaults.weather,...look.weather},cam={...defaults.camera,...look.camera};
 box.innerHTML=`<h3 class="prop-title">环境与相机</h3>${select('preset','光影预设',Object.fromEntries(Object.entries(looks).map(([k,v])=>[k,v.name])),look.preset)}<div class="subheading">环境光照 / 表面湿润</div>${[['sun_altitude_angle','太阳高度 / °',45],['sun_azimuth_angle','太阳方位 / °',265],['cloudiness','云量 / %',25],['wetness','湿润 / %',0],['precipitation','雨量 / %',0],['precipitation_deposits','积水 / %',0],['fog_density','雾浓度 / %',1],['fog_distance','雾起始 / m',80]].map(([k,n,v])=>field('weather.'+k,n,weather[k]??v,'number','step="1"')).join('')}<div class="subheading">相机外观</div>${[['gamma','Gamma',2.2],['exposure_compensation','曝光补偿',0],['bloom_intensity','Bloom',.08],['motion_blur_intensity','运动模糊',0]].map(([k,n,v])=>field('camera.'+k,n,cam[k]??v,'number','step=".05"')).join('')}<div class="subheading">预览相机</div>${field('capture.width','宽度',scene.camera.width)}${field('capture.height','高度',scene.camera.height)}${field('capture.fps','采样 Hz',scene.camera.fps)}${field('capture.fov','视场角 / °',scene.camera.fov)}<div class="actions"><button id="apply-look" class="primary">应用到实机预览</button><button id="reset-look">重置预设参数</button></div><p class="hint">天气与相机参数可即时应用。相机尺寸和视场角在下次预览/运行时生效。湿润效果取决于地图材质支持；修改不会自动改变路面摩擦。结束时恢复进入本次会话前的天气。</p>`;
 box.querySelectorAll('[data-key]').forEach(el=>el.onchange=()=>{checkpoint();const [group,key]=el.dataset.key.split('.');if(group==='preset'){look.preset=el.value;look.weather={};look.camera={};renderProperties()}else if(group==='capture')scene.camera[key]=+el.value;else look[group][key]=+el.value;changed()});
 $('apply-look').onclick=guarded(async()=>{await api('command',{type:'look',look});toast('光影已应用到 CARLA')});$('reset-look').onclick=()=>{checkpoint();look.weather={};look.camera={};changed();renderProperties()};
 }
}

async function refreshScenes(){sceneOptions=await api('scenes');$('scene-select').innerHTML=sceneOptions.map(s=>`<option value="${s.id}" ${s.id===scene?.id?'selected':''}>${esc(s.name)}</option>`).join('')}
async function loadScene(id){if(['running','paused','preview','starting'].includes(live.state))throw Error('请先停止当前会话，再切换场景');if(dirty&&!(await confirmChange('当前有未保存修改，仍然切换场景？')))return;scene=await api('scenes/'+id);$('camera-feed').removeAttribute('src');$('camera-feed').style.display='none';$('camera-empty').style.display='flex';previewTime=0;selected=scene.ego;eventId=scene.events[0]?.id;history=[];redo=[];dirty=false;$('dirty').textContent='已保存';render();rebuildActors();focus()}
async function save(){const result=await api('scenes',scene);scene=result.scene;render();dirty=false;$('dirty').textContent='已保存';await refreshScenes();toast('场景已保存；之前版本保留在历史目录')}
async function addActor(modelId='vehicle.tesla.model3'){if(motionLocked())throw Error('当前模式锁定车辆编排');checkpoint();const p=from3(orbit.target),pose=await api('snap',p);const id='actor_'+crypto.randomUUID().slice(0,8),ped=modelId.startsWith('walker');scene.actors.push({id,name:ped?'行人':modelId.includes('firetruck')?'消防车':modelId.includes('ninja')?'摩托车':'新车辆',model:modelId,...pose,color:'#79c8ba',speed:ped?5:40,offset:0,behavior:ped?'walker':'scripted',start_in_motion:!ped,spawn_at_start:true,snap:!ped,acceleration:2.5,deceleration:6,route:[]});selected=id;tab='actor';changed();rebuildActors();render();toast('已添加到视图中心，请拖动到目标位置。新增模型在下次预览时生成。')}
function addEvent(){if(motionLocked())return;checkpoint();const id='event_'+crypto.randomUUID().slice(0,8);scene.events.push({id,name:'新事件',enabled:true,trigger:{type:'time',value:5},action:{type:'speed',actor:selected||scene.ego,value:30}});eventId=id;tab='event';changed();render()}
function toggleRoute(){if(motionLocked())return;routeMode=!routeMode;$('route-mode').classList.toggle('active',routeMode);$('map-hint').textContent=routeMode?'左键点击道路添加路线点 · 再点“绘制路线”结束':'左键选中 / 拖动控件 · 右键平移 · 滚轮缩放';if(routeMode)gizmo.detach();else attach();renderProperties()}
async function start(preview){offlinePlaying=false;if(['running','paused','preview','starting'].includes(live.state))throw Error('请先停止当前会话');await api('validate',scene);const r=await api('start',{scene,preview});lastRun=r.run_id;manual=false;keys.clear();live.state='starting';updateMode();attach();$('camera-feed').src='/api/video?run='+r.run_id;$('camera-feed').style.display='block';$('camera-empty').style.display='none';toast(preview?'正在生成预览布置':'正在启动场景')}
$('snap').onchange=()=>{if(actor()){checkpoint();actor().snap=$('snap').checked;changed()}};
$('scene-select').onchange=guarded(e=>loadScene(e.target.value));$('save').onclick=guarded(save);$('add-actor').onclick=guarded(()=>addActor());document.querySelectorAll('[data-model]').forEach(el=>el.onclick=guarded(()=>addActor(el.dataset.model)));$('add-event').onclick=addEvent;
$('new').onclick=guarded(async()=>{if(['running','paused','preview','starting'].includes(live.state))throw Error('请先停止当前会话，再新建场景');if(dirty&&!(await confirmChange('新建空白场景，放弃当前未保存修改？')))return;const pose=await api('snap',from3(orbit.target));scene={version:2,mode:'motion',dt:.05,id:'scene_'+crypto.randomUUID().slice(0,8),name:'新的驾驶场景',map:map.name,duration:30,seed:42,ego:'ego',actors:[{id:'ego',name:'主车',model:'vehicle.tesla.model3',...pose,speed:30,offset:0,behavior:'scripted',start_in_motion:true,spawn_at_start:true,snap:true,color:'#b4e3d8',route:[],acceleration:2.5,deceleration:6}],events:[],look:{preset:'clear',weather:{},camera:{}},camera:{width:1280,height:720,fps:20,fov:100}};selected='ego';eventId=null;tab='actor';history=[];changed();rebuildActors();render();focus()});
$('duplicate').onclick=guarded(async()=>{checkpoint();scene.id='scene_'+crypto.randomUUID().slice(0,8);scene.name+=' 副本';await save();render()});
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(scene,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=scene.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)};
$('import').onclick=()=>$('import-file').click();$('import-file').onchange=guarded(async e=>{const file=e.target.files[0];if(!file)return;const s=JSON.parse(await file.text());const normalized=await api('validate',s);checkpoint();scene=normalized.scene;selected=scene.ego;eventId=scene.events[0]?.id;changed();rebuildActors();render();focus();toast('已导入，点击保存写入场景库')});
$('scene-name').onchange=e=>{checkpoint();scene.name=e.target.value;changed()};$('duration').onchange=e=>{checkpoint();scene.duration=+e.target.value;changed()};document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>{tab=el.dataset.tab;render()});
$('translate').onclick=()=>{gizmo.setMode('translate');gizmo.showX=true;gizmo.showY=false;gizmo.showZ=true;$('translate').classList.add('active');$('rotate').classList.remove('active');requestRender=true};
$('rotate').onclick=()=>{gizmo.setMode('rotate');gizmo.showX=false;gizmo.showY=true;gizmo.showZ=false;$('rotate').classList.add('active');$('translate').classList.remove('active');requestRender=true};
$('focus').onclick=focus;$('perspective').onclick=focus;$('top').onclick=()=>{const p=actor()?to3(actor()):orbit.target;orbit.target.copy(p);camera.position.copy(p).add(new THREE.Vector3(.01,90,.01));camera.up.set(0,0,-1);orbit.update();requestRender=true};$('route-mode').onclick=toggleRoute;
$('preview').onclick=guarded(()=>start(true));$('play').onclick=guarded(()=>start(false));$('stop').onclick=guarded(async()=>{await api('command',{type:'stop'});manual=false;toast('正在停止并清理本次参与者')});$('pause').onclick=guarded(()=>api('command',{type:live.state==='paused'?'resume':'pause'}));
$('camera-view').onchange=guarded(e=>api('command',{type:'camera',actor:scene.ego,view:e.target.value}));$('snapshot').onclick=()=>{const a=document.createElement('a');a.href='/api/frame?t='+Date.now();a.download=scene.id+'_preview.jpg';a.click()};
async function refreshRuns(){const runs=await api('runs');$('runs').innerHTML=runs.slice(0,7).map(r=>`<div class="run-item"><b>${esc(r.name.slice(0,18))}</b><small>${esc(r.state)} · ${r.elapsed.toFixed(1)}s</small><a href="/api/runs/${r.id}/telemetry.csv">轨迹</a> · <a href="/api/runs/${r.id}/events.json">事件</a> · <a href="/api/runs/${r.id}/scene.json">配置</a></div>`).join('')}
let polling=false;setInterval(async()=>{if(polling)return;polling=true;try{const old=live.state;live=await api('status');$('run-state').textContent=({idle:'尚未运行',starting:'启动中',preview:'布置预览',running:'运行中',paused:'已暂停',finished:'已结束',error:'运行异常'})[live.state]||live.state;$('clock').textContent=(live.elapsed||0).toFixed(1)+' s';$('fps').textContent=live.camera_fps?live.camera_fps.toFixed(1)+' FPS':'';$('pause').textContent=live.state==='paused'?'▶ 继续':'Ⅱ 暂停';
 if(['running','paused','preview'].includes(live.state)&&!$('camera-feed').getAttribute('src')){$('camera-feed').src='/api/video';$('camera-feed').style.display='block';$('camera-empty').style.display='none'}if(['running','paused','preview'].includes(live.state)){gizmo.detach();for(const [id,s] of Object.entries(live.actors||{})){const o=actorMeshes.get(id);if(o){o.position.copy(to3(s));o.rotation.y=s.yaw*Math.PI/180}}requestRender=true}
 if(old!==live.state&&['finished','error'].includes(live.state)){manual=false;keys.clear();rebuildActors();await refreshRuns();if(live.error)toast(live.error,true)}
 $('log').innerHTML=[...(live.events||[]).slice(-9).map(e=>`<div class="${e.error?'error':''}">${(e.time||0).toFixed(1)}s · ${esc(e.id||'')} ${esc(actionNames[e.type]||e.type)} ${esc(e.error||'')}</div>`),...(live.collisions||[]).slice(-3).map(c=>`<div class="error">${c.time.toFixed(1)}s · 碰撞 ${esc(c.actor)} / ${esc(c.other)}</div>`)].join('');if(scene){renderEvents();updateLive();updateMode()}
 }catch(e){$('run-state').textContent='本地服务连接中断'}finally{polling=false}},500);
$('research').onclick=()=>window.open('/research/index.html','_blank');
async function initialize(){const conn=await api('connection');looks=conn.looks;$('connection').textContent=conn.connected?'● '+conn.map:'○ CARLA 未连接';if(!conn.connected){$('map-loading').textContent='请启动 CARLA 后点击刷新';throw Error(conn.error)}const [m,blueprints]=await Promise.all([api('map'),api('blueprints')]);map=m;catalog=blueprints;drawMap();await refreshScenes();if(!scene){live=await api('status');if(['running','paused','preview','starting'].includes(live.state)){scene=await api('current-scene');selected=scene.ego;eventId=scene.events[0]?.id;render();rebuildActors();focus()}else if(sceneOptions.length)await loadScene(sceneOptions.find(s=>s.id==='Scene1_01')?.id||sceneOptions[0].id)}await refreshRuns();toast('道路与场景库已就绪')}
$('refresh').onclick=guarded(initialize);
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});

// V2 authoring: fixed recordings, timeline clips, rehearsal, and explicit input ownership.
let previewTime=0,offlinePlaying=false,planResult=null,planTimer=null,planSerial=0,planKey='',presets={};
let manualSource='keyboard',inputSeq=0,inputBusy=false,takePending=false,seekTimer=null,lastLockState=null;
const keys=new Set();
const activeSession=()=>['starting','running','paused','preview'].includes(live.state);
const motionLocked=()=>scene?.mode==='environment'||activeSession();
const selectedClip=()=>actor()?.clips?.find(c=>c.id===sequencer.selected);
const sequencer=new Sequencer({scene:()=>scene,actorId:()=>selected,locked:motionLocked,
 selectActor,selectClip:(aid,cid)=>{selected=aid;sequencer.selected=cid;tab='clip';renderList();renderProperties();document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===tab));document.querySelectorAll('[data-clip]').forEach(el=>el.classList.toggle('selected',el.dataset.clip===cid))},
 beforeEdit:checkpoint,afterEdit:()=>{changed();renderProperties()},validate:()=>api('validate',scene),
 seek:t=>seek(t),addClip:type=>guarded(addClip)(type),error:msg=>toast(msg,true),dragInfo:msg=>$('status-message').textContent=msg});
function updateMode(){if(!scene)return;const env=scene.mode==='environment',locked=motionLocked();
 $('mode-motion').classList.toggle('active',!env);$('mode-environment').classList.toggle('active',env);$('mode-badge').textContent=env?'固定轨迹 / 环境调色':'运动编排 / 物理录制';
 $('lock-card').textContent=env?'已锁定基准 '+scene.locked_take+'。位置、速度、时间轴保持不变，可调整环境与相机。手动接管会将本次标记为轨迹偏离。':'先编排运动并录制，再从录制库选择基准，进行固定轨迹的环境对照。';
 for(const id of ['add-actor','add-event','duration','snap','translate','rotate','route-mode'])$(id).disabled=locked;
 document.querySelectorAll('[data-model],[data-add-clip],.preset-card').forEach(b=>b.disabled=locked);
 $('play').textContent=env?'▶ 重放并录制':'▶ 运行并录制';$('mode-motion').disabled=activeSession();$('mode-environment').disabled=activeSession();$('take-library').disabled=activeSession();
 for(const id of ['new','import','scene-select','duplicate'])$(id).disabled=activeSession();
 $('manual').disabled=!['running','paused'].includes(live.state);$('auto').disabled=!['running','paused'].includes(live.state)||live.control?.owner==='auto';
 $('rehearse').disabled=activeSession();$('preview').disabled=activeSession();$('play').disabled=activeSession();$('stop').disabled=!activeSession();$('pause').disabled=!['running','paused'].includes(live.state);
 $('event-count').textContent=scene.events.length?'('+scene.events.length+')':'';
 if(lastLockState!==locked){lastLockState=locked;renderProperties()}
 if(locked){routeMode=false;$('route-mode').classList.remove('active');gizmo.detach()}
}
function renderProperties(){if(tab==='clip')renderClipProperties();else renderLegacyProperties();
 if(motionLocked()&&['actor','event','clip'].includes(tab)){
  $('properties').querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=true);
  const msg=document.createElement('p');msg.className='mode-notice';msg.textContent=scene.mode==='environment'?'基准轨迹已锁定。切回运动编排后可修改；修改后需要重新录制。':'运行中保持编排不变。停止后可编辑；手动接管和环境调整仍可使用。';$('properties').prepend(msg)
 }
 if(tab==='actor'&&actor()&&!motionLocked()){
  const points=$('properties').querySelectorAll('.route-point');points.forEach((el,i)=>{const p=actor().route[i],button=el.querySelector('button');el.innerHTML=`<span>${i+1}</span><input aria-label="路线点 ${i+1} X" data-axis="x" type="number" step=".1" value="${p.x.toFixed(1)}"><input aria-label="路线点 ${i+1} Y" data-axis="y" type="number" step=".1" value="${p.y.toFixed(1)}">`;el.append(button);el.querySelectorAll('input').forEach(input=>input.onchange=()=>{checkpoint();p[input.dataset.axis]=+input.value;changed();drawRoutes()})})
 }
}
function clipFields(c){let html=field('start','开始 / s',c.start,'number','min="0" step=".1"')+field('duration','持续 / s',c.duration,'number','min=".1" step=".1"');
 if(c.type==='speed')html+=field('value','目标速度 km/h',c.value,'number','min="0" max="180" step="1"')+select('easing','速度过渡',{linear:'线性变化',smooth:'平滑变化'},c.easing||'linear');
 if(c.type==='brake')html+=field('value','制动强度 0–1',c.value,'number','min="0" max="1" step=".05"');
 if(c.type==='lane_change')html+=select('direction','方向',{left:'左侧车道',right:'右侧车道'},c.direction)+field('lanes','跨越车道',c.lanes,'number','min="1" max="3" step="1"');
 if(c.type==='follow')html+=select('target','跟随车辆',Object.fromEntries(scene.actors.filter(a=>a.id!==selected&&a.model.startsWith('vehicle.')).map(a=>[a.id,a.name])),c.target)+field('reaction','反应延迟 / s',c.reaction,'number','min="0" max="5" step=".1"')+field('gap','最小车距 / m',c.gap,'number','min="0" step=".5"')+field('headway','时间车距 / s',c.headway,'number','min=".1" max="5" step=".1"');
 if(c.type==='lights')html+=select('value','灯光',{0:'关闭',3:'示宽 + 近光',17:'右转向',33:'左转向',49:'双闪'},c.value);
 return html+`<label class="field"><span>启用</span><input data-key="enabled" type="checkbox" ${c.enabled!==false?'checked':''}></label>`;
}
function renderClipProperties(){const c=selectedClip(),a=actor();if(!c){$('properties').innerHTML='<h3 class="prop-title">时间轴片段</h3><p class="hint">选中车辆后添加速度、变道、跟车或制动片段。拖动片段移动时间，拖动右边缘修改持续时间。</p>';return}
 const frames=planResult?.tracks[a.id]?.frames||[],max=Math.max(60,...frames.map(p=>p[5]));
 $('properties').innerHTML=`<h3 class="prop-title">${esc(a.name)} · ${clipNames[c.type]}</h3>${clipFields(c)}<div class="subheading">速度预演 / km/h <small>0–${Math.ceil(max)}</small></div><svg class="speed-chart" viewBox="0 0 260 90" preserveAspectRatio="none"><path d="M0 75H260 M0 45H260 M0 15H260" stroke="#294552" fill="none"/><polyline stroke="#81e2c1" stroke-width="2" fill="none" points="${frames.map(f=>`${f[0]/scene.duration*260},${85-f[5]/max*75}`).join(' ')}"/></svg><p class="hint">速度为目标或预演估计，实际物理速度受加减速、转向与跟车约束。跟车预演显示速度上限。变道片段结束后保持新车道偏移。</p><div class="actions"><button id="clone-clip">复制片段</button><button id="delete-clip" class="danger">删除片段</button></div>`;
 $('properties').querySelectorAll('[data-key]').forEach(el=>{el.oninput=()=>{if(motionLocked())return;checkpoint();c[el.dataset.key]=el.type==='checkbox'?el.checked:el.type==='number'||(c.type==='lights'&&el.dataset.key==='value')?+el.value:el.value;changed();sequencer.render()};el.onchange=guarded(async()=>{await api('validate',scene)})});
 $('delete-clip').onclick=()=>{checkpoint();a.clips=a.clips.filter(x=>x.id!==c.id);sequencer.selected=null;changed();render()};
 $('clone-clip').onclick=guarded(async()=>{const copy={...c,id:'clip_'+crypto.randomUUID().slice(0,8),start:c.start+c.duration};if(copy.start+copy.duration>scene.duration)throw Error('片段之后没有足够时长，请先延长场景');checkpoint();a.clips.push(copy);try{await api('validate',scene)}catch(e){a.clips.pop();throw e}sequencer.selected=copy.id;changed();render()});
}
async function addClip(type){if(motionLocked())throw Error('请在运动编排模式停止运行后编辑');const a=actor();if(!a?.model.startsWith('vehicle.'))throw Error('请选择车辆');const c={id:'clip_'+crypto.randomUUID().slice(0,8),type,start:Math.round(previewTime*10)/10,duration:3,enabled:true};
 const conflicts=x=>type===x.type||['speed','brake'].includes(type)&&['speed','brake'].includes(x.type);
 for(const x of [...(a.clips||[])].filter(conflicts).sort((a,b)=>a.start-b.start))if(c.start<x.start+x.duration&&c.start+c.duration>x.start)c.start=x.start+x.duration;
 c.duration=Math.min(c.duration,scene.duration-c.start);if(c.duration<.1)throw Error('没有足够空白时长，请移动播放头或延长场景');
 if(type==='speed')Object.assign(c,{value:40,easing:'smooth'});if(type==='brake')c.value=.8;if(type==='lane_change')Object.assign(c,{direction:'left',lanes:1});if(type==='lights')c.value=3;
 if(type==='follow'){const target=scene.actors.find(b=>b.id!==a.id&&b.model.startsWith('vehicle.'));if(!target)throw Error('请先添加另一辆车作为跟随目标');Object.assign(c,{target:target.id,reaction:.8,gap:4,headway:1.2})}
 checkpoint();a.clips??=[];a.clips.push(c);sequencer.selected=c.id;tab='clip';changed();render();
}
function schedulePlan(){clearTimeout(planTimer);if(!scene)return;planTimer=setTimeout(()=>refreshPlan().catch(e=>{$('plan-state').textContent='需修正编排：'+e.message;$('status-message').textContent=e.message}),400)}
async function refreshPlan(force=false){if(!scene||activeSession())return;const key=JSON.stringify(scene);if(!force&&key===planKey)return;const serial=++planSerial;$('plan-state').textContent='计算道路路线与速度预演…';const result=await api('plan',scene);if(serial!==planSerial||JSON.stringify(scene)!==key)return;planKey=key;planResult=result;sequencer.plan=result;sequencer.render();drawPlannedRoutes();seek(previewTime,false);$('plan-state').textContent=result.locked?'已录制的实际轨迹 · 可拖动时间轴查看':'估计运动预演 · 实际轨迹以 CARLA 录制为准';$('status-message').textContent=result.warnings?.[0]||'路线与时间轴已更新';}
function drawPlannedRoutes(){drawRoutes();if(!planResult)return;for(const [id,track] of Object.entries(planResult.tracks)){const frames=track.frames.filter((_,i)=>i%3===0);if(frames.length<2)continue;const g=new THREE.BufferGeometry().setFromPoints(frames.map(f=>to3({x:f[1],y:f[2],z:f[3]+.2})));routeGroup.add(new THREE.Line(g,new THREE.LineBasicMaterial({color:id===selected?0x7ce5c2:0x64849b,transparent:true,opacity:id===selected?.8:.35})))}requestRender=true}
function sampleFrames(frames,t){let lo=0,hi=frames.length-1;while(lo<hi){const mid=Math.floor((lo+hi)/2);if(frames[mid][0]<t)lo=mid+1;else hi=mid}const b=frames[lo],a=frames[Math.max(0,lo-1)],u=Math.max(0,Math.min(1,(t-a[0])/Math.max(1e-9,b[0]-a[0])));return {x:a[1]+(b[1]-a[1])*u,y:a[2]+(b[2]-a[2])*u,z:a[3]+(b[3]-a[3])*u,yaw:a[4]+((b[4]-a[4]+540)%360-180)*u,speed:a[5]+(b[5]-a[5])*u}}
function seek(t,notify=true){previewTime=t;sequencer.setTime(t);if(['running','paused','starting'].includes(live.state)){if(notify)toast('运行中的播放头由仿真驱动；请停止后预演或使用实机预览');return}
 if(live.state==='preview'){if(notify){clearTimeout(seekTimer);seekTimer=setTimeout(()=>api('command',{type:'seek',time:t}).catch(e=>toast(e.message,true)),100)}return}
 for(const [id,track] of Object.entries(planResult?.tracks||{})){const obj=actorMeshes.get(id);if(!obj||!track.frames.length)continue;const p=sampleFrames(track.frames,t);obj.position.copy(to3(p));obj.rotation.y=p.yaw*Math.PI/180;if(id===scene.ego)$('speed-readout').textContent=Math.round(p.speed)}
 if(t>.001)gizmo.detach();else attach();requestRender=true;
}
let lastAnimation=performance.now();function animateRehearsal(now){const dt=Math.min(.1,(now-lastAnimation)/1000);lastAnimation=now;if(offlinePlaying){seek(Math.min(scene.duration,previewTime+dt));if(previewTime>=scene.duration){offlinePlaying=false;$('rehearse').textContent='▷ 预演'}}requestAnimationFrame(animateRehearsal)}requestAnimationFrame(animateRehearsal);
$('rehearse').onclick=guarded(async()=>{if(activeSession())return;await refreshPlan(true);offlinePlaying=!offlinePlaying;if(offlinePlaying&&previewTime>=scene.duration)previewTime=0;$('rehearse').textContent=offlinePlaying?'Ⅱ 停止预演':'▷ 预演'});
function renderPresets(){const icons={cruise:'→',stop_go:'↗',lead_brake:'Ⅱ',cut_in:'↘',overtake:'⇄',follow:'⇢',parked:'P'};$('preset-list').innerHTML=Object.entries(presets).map(([id,p])=>`<button class="preset-card" data-preset="${id}"><span class="preset-icon">${icons[id]}</span><span><b>${esc(p.name)}</b><small>${esc(p.description)}</small></span></button>`).join('');document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=guarded(async()=>{if(motionLocked())return;const a=actor();if(!a?.model.startsWith('vehicle.'))throw Error('请选择一辆车');let target=scene.actors.find(x=>x.id!==selected&&x.model.startsWith('vehicle.'))?.id;
 if(b.dataset.preset==='follow'){if(!target)throw Error('跟车需要另一辆车');const choices=scene.actors.filter(x=>x.id!==selected&&x.model.startsWith('vehicle.'));if(choices.length>1){showModal('选择跟车目标',`<p class="hint">预设将替换选中车辆的时间轴。旧条件事件中的运动动作会停用。</p><select id="follow-target">${options(Object.fromEntries(choices.map(x=>[x.id,x.name])),target)}</select><button id="confirm-preset" class="primary">应用跟车预设</button>`);$('confirm-preset').onclick=guarded(async()=>{await applyPreset(b.dataset.preset,$('follow-target').value);$('modal').close()});return}}
 await applyPreset(b.dataset.preset,target)}));updateMode()}
async function applyPreset(name,target){checkpoint();const r=await api('preset',{scene,actor:selected,preset:name,target});scene=r.scene;sequencer.selected=actor().clips?.[0]?.id;tab=sequencer.selected?'clip':'actor';previewTime=0;changed();rebuildActors();render();toast('已应用 '+presets[name].name+(r.disabled_events?.length?'；已停用冲突的旧运动事件':''))}
function showModal(title,html){$('modal-title').textContent=title;$('modal-body').innerHTML=html;$('modal').showModal()}
$('modal-close').onclick=()=>$('modal').close();
async function takeLibrary(){if(activeSession())throw Error('请先停止运行');const takes=await api('takes');showModal('选择基准轨迹',`<p class="hint">先在运动编排模式运行并录制。选择实际录制轨迹后，仅调整天气、光照、相机；车辆位置、路线和速度锁定。带手动记录也可以作为新的基准。</p>${takes.length?takes.map(t=>`<div class="take-row"><div><b>${esc(t.name)}</b><small>${esc(t.id)} · ${t.duration.toFixed(1)} s · ${t.frames} 帧 ${t.manual_override?'· 含手动驾驶':''}</small></div><button data-take="${t.id}">锁定此轨迹</button></div>`).join(''):'<p>暂无可用录制，请先运行一个运动场景。</p>'}`);document.querySelectorAll('[data-take]').forEach(b=>b.onclick=guarded(()=>loadTake(b.dataset.take)))}
async function loadTake(id){if(dirty&&!(await confirmChange('切换到录制基准会替换当前编排，继续？')))return;const take=await api('takes/'+id);checkpoint();scene=clone(take.scene);scene.id='env_'+crypto.randomUUID().slice(0,8);scene.name+=' · 环境对照';scene.mode='environment';scene.locked_take=id;selected=scene.ego;tab='look';previewTime=0;planKey='';changed();$('modal').close();rebuildActors();render();focus();await refreshPlan(true);sequencer.fit();toast('已锁定实际轨迹，可在环境面板调整光照与天气')}
$('take-library').onclick=guarded(takeLibrary);$('mode-environment').onclick=guarded(takeLibrary);
$('mode-motion').onclick=guarded(async()=>{if(activeSession())return;if(scene.mode==='environment'){checkpoint();scene.mode='motion';delete scene.locked_take;scene.id='scene_'+crypto.randomUUID().slice(0,8);scene.name=scene.name.replace(' · 环境对照','')+' · 运动副本';tab='actor';changed();render();attach();toast('已创建可编辑运动副本；再次锁定轨迹前需重新录制')}});
function liveView(force){const enabled=force??!$('stage').classList.contains('live-view');$('stage').classList.toggle('live-view',enabled);$('view-live').textContent=enabled?'返回场景 ↙':'驾驶画面 ↗';$('stage').focus()}
$('view-live').onclick=()=>liveView();
function updateLive(){const control=live.control||{owner:'auto'},ego=live.actors?.[scene.ego];if(ego)$('speed-readout').textContent=Math.round(ego.speed);$('owner-readout').textContent=control.owner==='auto'?'AUTO / 自动驾驶':({keyboard:'KEYBOARD / 键盘',gamepad:'GAMEPAD / 手柄',wheel:'WHEEL / 方向盘'})[control.owner]||control.owner;$('driving-hud').classList.toggle('manual',control.owner!=='auto');$('manual').classList.toggle('active',control.owner!=='auto');$('input-health').textContent=control.failsafe?'输入已中断 · 保持制动，控制权仍为手动':live.trajectory_status==='manual_override'?'手动接管已改变主车轨迹 · 背景车继续重放':'M 接管 · WASD 驾驶 · R 自动';
 if(['running','paused','preview'].includes(live.state)){sequencer.setTime(live.elapsed||0);previewTime=live.elapsed||0}if(control.owner==='auto')manual=false;
 if(live.trajectory_status==='manual_override')$('mode-badge').textContent='主车轨迹已偏离基准 / 背景车保持重放';
}
async function takeover(source=manualSource){if(takePending)return;if(!['running','paused'].includes(live.state))throw Error('请先运行场景；实机布置预览不进行物理驾驶');takePending=true;manual=false;keys.clear();const oldEpoch=live.control?.epoch??-1;
 try{await api('command',{type:'takeover',owner:source});const deadline=performance.now()+3500;let acknowledged=false;while(performance.now()<deadline){const s=await api('status');if(s.control?.owner===source&&s.control.epoch>oldEpoch){live=s;acknowledged=true;break}await new Promise(r=>setTimeout(r,50))}if(!acknowledged)throw Error('接管尚未确认，请检查运行提示');manualSource=source;inputSeq=0;manual=true;liveView(true);updateLive();toast('已接管。输入中断会制动，时间轴不会收回控制权。')}
 finally{takePending=false}
}
async function releaseControl(){manual=false;keys.clear();await api('command',{type:'release'});toast('恢复自动沿线控制；手动期间的轨迹偏离会保留在记录中')}
$('manual').onclick=guarded(()=>takeover());$('auto').onclick=guarded(releaseControl);
let inputConfig={source:'keyboard',index:0,steerAxis:0,steerCenter:0,steerSpan:1,invert:false,deadzone:.06,throttleMode:'button',throttleIndex:7,throttleRest:-1,throttleFull:1,brakeMode:'button',brakeIndex:6,brakeRest:-1,brakeFull:1};
try{Object.assign(inputConfig,JSON.parse(localStorage.getItem('hyxInput')||'{}'))}catch{}manualSource=inputConfig.source;
function gamepadControl(){const pad=navigator.getGamepads?.()[inputConfig.index];if(!pad?.connected)return null;const axis=(pad.axes[inputConfig.steerAxis]??0)-inputConfig.steerCenter,dead=inputConfig.deadzone;let steer=Math.abs(axis)<dead?0:Math.sign(axis)*(Math.abs(axis)-dead)/Math.max(.01,inputConfig.steerSpan-dead);if(inputConfig.invert)steer=-steer;const pedal=k=>{if(inputConfig[k+'Mode']==='button')return pad.buttons[inputConfig[k+'Index']]?.value??0;const rest=inputConfig[k+'Rest'],full=inputConfig[k+'Full'];if(Math.abs(full-rest)<.01)return 0;return Math.max(0,Math.min(1,((pad.axes[inputConfig[k+'Index']]??rest)-rest)/(full-rest)))};return {steer:Math.max(-1,Math.min(1,steer)),throttle:pedal('throttle'),brake:pedal('brake')}}
async function sendDrivingInput(){if(inputBusy||!manual||!document.hasFocus()||document.visibilityState!=='visible'||!['running','paused'].includes(live.state)||live.control?.owner!==manualSource)return;let value=manualSource==='keyboard'?{steer:keys.has('a')?-.6:keys.has('d')?.6:0,throttle:keys.has('w')?.75:0,brake:keys.has('s')||keys.has(' ')?1:0}:gamepadControl();if(!value)return;inputBusy=true;try{await api('input',{run_id:live.run_id,epoch:live.control.epoch,seq:++inputSeq,...value})}catch{manual=false}finally{inputBusy=false}}setInterval(sendDrivingInput,50);
window.addEventListener('blur',()=>{keys.clear();manual=false});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();manual=false}});
function undoEdit(forward=false){if(activeSession())return;const source=forward?redo:history,dest=forward?history:redo;if(!source.length)return;dest.push(JSON.stringify(scene));scene=JSON.parse(source.pop());selected=scene.ego;sequencer.selected=null;changed();rebuildActors();render()}
$('undo').onclick=()=>undoEdit();$('redo').onclick=()=>undoEdit(true);
document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||$('modal').open||$('confirm').open)return;const k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&['z','y','s'].includes(k)){e.preventDefault();if(k==='s')guarded(save)();else undoEdit(k==='y'||e.shiftKey);return}if(k==='m'&&!e.repeat){e.preventDefault();guarded(()=>takeover())();return}if(k==='r'&&!e.repeat&&activeSession()){e.preventDefault();guarded(releaseControl)();return}if(manual&&['w','a','s','d',' '].includes(k)){keys.add(k);sendDrivingInput();e.preventDefault();return}if(activeSession())return;if(k==='f')focus();if(k==='w')$('translate').click();if(k==='e')$('rotate').click();if(k===' '&&!e.repeat){e.preventDefault();$('rehearse').click()}});document.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());sendDrivingInput()});
$('input-settings').onclick=()=>{showModal('驾驶输入设置',`<p class="hint">浏览器需要先检测到设备：连接后按一次按钮。键盘无需校准；手柄默认使用轴 0 转向、按钮 7 油门、按钮 6 制动。方向盘可选择踏板轴并记录松开/踩到底的值。该界面不提供力反馈。</p><div class="modal-grid"><div>${select('source','输入设备',{keyboard:'键盘',gamepad:'手柄',wheel:'方向盘'},inputConfig.source)}${field('index','设备序号',inputConfig.index,'number','min="0" max="7"')}${field('steerAxis','转向轴',inputConfig.steerAxis,'number','min="0" max="31"')}${field('steerCenter','转向中心',inputConfig.steerCenter,'number','step=".01"')}${field('steerSpan','转向半量程',inputConfig.steerSpan,'number','min=".1" max="2" step=".05"')}${field('deadzone','转向死区',inputConfig.deadzone,'number','min="0" max=".5" step=".01"')}<label class="field"><span>转向反向</span><input data-key="invert" type="checkbox" ${inputConfig.invert?'checked':''}></label></div><div>${['throttle','brake'].map(k=>`<h3>${k==='throttle'?'油门':'制动'}</h3>${select(k+'Mode','来源',{button:'按钮',axis:'轴'},inputConfig[k+'Mode'])}${field(k+'Index','按钮/轴序号',inputConfig[k+'Index'],'number','min="0" max="31"')}${field(k+'Rest','松开时轴值',inputConfig[k+'Rest'],'number','step=".01"')}${field(k+'Full','踩到底轴值',inputConfig[k+'Full'],'number','step=".01"')}`).join('')}</div></div><pre id="input-meter" class="input-meter"></pre><button id="save-input" class="primary">保存输入设置</button>`);$('save-input').onclick=()=>{$('modal-body').querySelectorAll('[data-key]').forEach(el=>inputConfig[el.dataset.key]=el.type==='checkbox'?el.checked:el.type==='number'?+el.value:el.value);localStorage.setItem('hyxInput',JSON.stringify(inputConfig));manualSource=inputConfig.source;manual=false;$('modal').close();toast('设置已保存；点击接管启用新输入设备')};};
setInterval(()=>{const meter=$('input-meter');if(!meter)return;const pads=[...(navigator.getGamepads?.()||[])].filter(Boolean);meter.textContent=pads.length?pads.map(p=>`[${p.index}] ${p.id}\n轴: ${p.axes.map((v,i)=>i+':'+v.toFixed(2)).join(' ')}\n按钮: ${p.buttons.map((b,i)=>i+':'+b.value.toFixed(1)).join(' ')}`).join('\n\n'):'尚未检测到手柄或方向盘。连接后按设备上的按钮，再观察此处。'},200);
// Seed presets independently; initialize retains the existing connection and scene loader.
api('connection').then(r=>{presets=r.presets||{};renderPresets()}).catch(()=>{});
guarded(initialize)();
